let dataTransformerTable = [
  ///////////// HOSPITAL 1, PATIENTS //////////////////////
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "PatientID",
    convertMethod: undefined,
    dstColName: "OriginalPatientID",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "MRN",
    convertMethod: undefined,
    dstColName: "MRN",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "PatientDOB",
    convertMethod: `{"dateFrom": {"format":"MM/dd/yyyy hh:mm"}}`,
    dstColName: "DOB",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "IsDeceased",
    convertMethod: `{"enum": {"from":["Active", "Hospice", "Deceased"], "to": ["Active", "Hospice", "Deceased"]}}`,
    dstColName: "LifeStatus",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "DOD_TS",
    convertMethod: `{"dateFrom": {"format":"m/dd/yyyy h:MM:ss TT"}}`,
    dstColName: "DeathDate",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "LastName",
    convertMethod: undefined,
    dstColName: "LastName",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "FirstName",
    convertMethod: undefined,
    dstColName: "FirstName",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "Gender",
    convertMethod: `{"enum": {"from":["Male-to-Female", "Female-to-Male", "Trans Woman", "Transgender Woman", "Transgender Female", "Transgender Male", "Trans Male"], "to": ["M2F", "F2M", "Trans Female", "Trans Female", "Trans Female", "Trans Male", "Trans Male"]}}`,
    //there's no consistancy in enums, there must be more! ask hospital1 to give complete list
    dstColName: "Gender",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "Sex",
    convertMethod: `{"enum": {"from":["Male", "Female"], "to": ["Male", "Female"]}}`,
    dstColName: "Sex",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "Address",
    convertMethod: undefined,
    dstColName: "Address",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "City",
    convertMethod: undefined,
    dstColName: "City",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "State",
    convertMethod: undefined,
    dstColName: "State",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "ZipCode",
    convertMethod: undefined,
    dstColName: "ZipCode",
  },
  {
    hospitalId: 1,
    tableName: "Patients",
    srcColName: "LastModifiedDate",
    convertMethod: `{"dateFrom": {"format":"M/dd/yyyy hh:mm:ss TT"}}`,
    dstColName: "LastModifiedDateBySrc",
  },
  ///////////// HOSPITAL 2, PATIENTS //////////////////////
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "PatientId",
    convertMethod: undefined,
    dstColName: "OriginalPatientID",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "MRN",
    convertMethod: undefined,
    dstColName: "MRN",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "PatientDOB",
    convertMethod: `{"dateFrom": {"format":"MM/dd/yyyy"}}`,
    dstColName: "DOB",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "IsPatientDeceased",
    srcEnum: `{"enum": {"from":["N", "Y"], "to": ["Active", "Deceased"]}}`,
    dstColName: "LifeStatus",
    dstEnum: ["Active", "Deceased"],
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "DeathDate",
    convertMethod: `{"dateFrom": {"format":"MM/dd/yyyy"}}`, //TODO ask hospital2 for their date format, i have no example of it
    dstColName: "DeathDate",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "LastName",
    convertMethod: undefined,
    dstColName: "LastName",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "FirstName",
    convertMethod: undefined,
    dstColName: "FirstName",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "Gender",
    convertMethod: undefined, //TODO ask hospital2 for enums of gender, i have no example of it
    dstColName: "Gender",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "Sex",
    convertMethod: `{"enum": {"from":["Male", "Female"], "to": ["Male", "Female"]}}`,
    dstColName: "Sex",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "AddressLine",
    convertMethod: undefined,
    dstColName: "Address",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "AddressCity",
    convertMethod: undefined,
    dstColName: "City",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "AddressState",
    convertMethod: undefined,
    dstColName: "State",
  },
  {
    hospitalId: 2,
    tableName: "Patients",
    srcColName: "AddressZipCode",
    convertMethod: undefined,
    dstColName: "ZipCode",
  },
  ///////////// HOSPITAL 1, TREATMENTS //////////////////////
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "PatientID",
    convertMethod: undefined,
    dstColName: "OriginalPatientID",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "StartDate",
    convertMethod: `{"dateFrom": {"format":"MM/dd/yyyy h:mm"}}`,
    dstColName: "StartDate",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "EndDate",
    convertMethod: `{"dateFrom": {"format":"MM/dd/yyyy hh:mm"}}`,
    dstColName: "EndDate",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "Active",
    convertMethod: `{"enum": {"from":["Ordered"], "to": ["Active"]}}`, //TODO ask hospital1 what other enums are valid here
    dstColName: "TreatmentStatus",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "DisplayName",
    convertMethod: undefined,
    dstColName: "DisplayName",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "Diagnoses",
    convertMethod: undefined,
    dstColName: "Diagnoses",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "TreatmentLine",
    convertMethod: undefined,
    dstColName: "TreatmentLine",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "CyclesXDays",
    convertMethod: undefined,
    dstColName: "CyclesXDays",
  },
  {
    hospitalId: 1,
    tableName: "Treatments",
    srcColName: "TreatmentID",
    convertMethod: undefined,
    dstColName: "TreatmentID",
  },
  ///////////// HOSPITAL 2, TREATMENTS //////////////////////
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "PatientId",
    convertMethod: undefined,
    dstColName: "OriginalPatientID",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "ProtocolID",
    convertMethod: undefined,
    dstColName: "ProtocolID",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "StartDate",
    convertMethod: `{"dateFrom": {"format":"M/dd/yyyy"}}`,
    dstColName: "StartDate",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "EndDate",
    convertMethod: `{"dateFrom": {"format":"M/dd/yyyy"}}`,
    dstColName: "EndDate",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "Status",
    convertMethod: `{"enum": {"from":["Active"], "to": ["Active"]}}`, //TODO ask hospital2 what other enums are valid here
    dstColName: "TreatmentStatus",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "DisplayName",
    convertMethod: "undefined",
    dstColName: "DisplayName",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "AssociatedDiagnoses",
    convertMethod: undefined,
    dstColName: "Diagnoses",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "NumberOfCycles",
    convertMethod: undefined,
    dstColName: "NumberOfCycles",
  },
  {
    hospitalId: 2,
    tableName: "Treatments",
    srcColName: "TreatmentId",
    convertMethod: undefined,
    dstColName: "TreatmentID",
  },
];

module.exports = {
  dataTransformerTable,
};
